# Generated by Django 4.1.7 on 2023-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelapplication',
            name='hotel_image',
            field=models.FileField(upload_to='applications/<django.db.models.fields.CharField>'),
        ),
    ]
