# Generated by Django 4.1.7 on 2023-03-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotelmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_available',
            field=models.BooleanField(default=True),
        ),
    ]
