# Generated by Django 4.1.7 on 2023-04-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_room_room_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_available',
        ),
    ]
