# Generated by Django 4.1.7 on 2023-04-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_hotelapplication_hotel_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='room',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
    ]
