# Generated by Django 4.1.7 on 2023-04-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_remove_roombooking_room_roombooking_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='user',
        ),
    ]
