# Generated by Django 4.1.7 on 2023-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_roombooking_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='check_out_time',
            field=models.TimeField(null=True),
        ),
    ]
