# Generated by Django 4.1.7 on 2023-04-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_roombooking_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
