# Generated by Django 4.1.7 on 2023-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_roombooking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='housekeeping_required',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
