# Generated by Django 4.1.4 on 2023-04-03 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0016_roombooking_housekeeping_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hotel.hotelapplication",
            ),
        ),
    ]
