# Generated by Django 4.1.7 on 2023-04-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotelmanager'),
        ),
    ]
