# Generated by Django 4.1.4 on 2023-04-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0017_hotel_hotel"),
        ("hotel", "0018_hotel_latitude_hotel_longitude"),
    ]

    operations = []
