# Generated by Django 4.1.7 on 2023-04-14 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_remove_hotel_hotel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
