# Generated by Django 4.1.4 on 2023-04-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0019_merge_20230414_1005"),
        ("hotel", "0021_roombooking_room"),
    ]

    operations = []
